variables:
  DOCKER_HOST: tcp://docker:2375
  RELEASE_REGISTRY: docker.io
  RELEASE_IMAGE: index.docker.io/$RELEASE_USER
  IMAGE_NAME: docker
  DOCKER_BUILDKIT: 1

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker --version
    - echo "$RELEASE_PASSWORD" | docker login $RELEASE_REGISTRY --username $RELEASE_USER --password-stdin
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - echo "Build and push $RELEASE_IMAGE/$IMAGE_NAME$tag"
    - docker build --tag "$RELEASE_IMAGE/$IMAGE_NAME${tag}" --build-arg="GITHUB_TOKEN=$GITHUB_TOKEN" .
    - docker push "$RELEASE_IMAGE/$IMAGE_NAME${tag}"
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
    - if: $CI_COMMIT_BRANCH
      changes:
        - Dockerfile
